language: python

python:
  - "2.7"

services:
  - postgresql

cache:
  directories:
    - $HOME/.cache/pip

before_script:
  - psql -c 'create database wecron;' -U postgres
  - make syncdb

install:
  - pip install -r requirements.txt

script:  make test-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
