- hosts: wecron
  gather_facts: False

  vars:
    PROJ_HOME: /var/www/wecron
    PROJ_VENV: "{{ PROJ_HOME }}/.venv"
    CODE_HOME: "{{ PROJ_HOME }}/WeCron"
  # vars_files:
  # Put my secret keys to inventory file
  #   - keys.yml

  tasks:
    - name: Install system packages
      sudo: True
      apt: pkg="{{ item }}" state=installed
      with_items:
        - python2.7
        - python-dev
        - python-pip
        - git
        - supervisor
        - libpq-dev
        - ntpdate
        - libffi-dev
        - libssl-dev

### App
    - name: Create directories
      file: path="{{ item }}" state=directory mode=0775 owner="www-data" group="www-data"
      sudo: True
      with_items:
          - "{{ PROJ_HOME }}"
          - "{{ PROJ_HOME }}/log"

    - name: Install virtualenv
      sudo: True
      pip: name=virtualenv state=present version=1.11.4

    - name: Create a virtualenv for wecron
      shell: virtualenv "{{ PROJ_VENV }}"
             creates="{{ PROJ_VENV }}/bin/activate"
      notify:
        - Install python dependencies

    - name: Crontab for setting correct time
      cron: name="update time" minute="0" hour="0,12" job="/usr/sbin/ntpdate pool.ntp.org"
      sudo: True

    - name: Check python dependencies
      copy: src=../requirements.txt dest="{{ PROJ_HOME }}/requirements.txt"
      notify:
        - Install python dependencies

    - name: Install oneapm
      pip:
        name: blueware
        extra_args: '-i http://pypi.oneapm.com/simple'
        virtualenv: "{{ PROJ_VENV }}"

    - name: Update Makefile
      copy: src=../Makefile dest="{{ PROJ_HOME }}/Makefile"
      notify:
        - Load wecron with supervisord

    - name: Update code
      synchronize:
        src: ../WeCron
        dest: "{{ PROJ_HOME }}"
        owner: no
        group: no
        perms: yes
        delete: yes
        rsync_opts:
          - "--exclude-from='../.gitignore'"
      # sudo: True
      # copy:
      #     src: ../WeCron
      #     dest: "{{ PROJ_HOME }}"
      #     owner: www-data
      #     group: www-data
      #     mode: 0775
      notify:
        - Load wecron with supervisord

##### Nginx
    - name: Install nginx
      sudo: True
      apt: pkg=nginx state=installed update_cache=yes
      notify:
        - Start nginx

    - name: Update nginx config
      sudo: True
      template: src=conf/nginx.conf.j2 dest="/etc/nginx/sites-available/weixin.at"
      notify:
        # Handlers only run once after all tasks complete
        - Reload nginx

    - name: Link weixin.at config to site-available
      sudo: True
      file: src="/etc/nginx/sites-available/weixin.at" dest="/etc/nginx/sites-enabled/weixin.at" state=link

#### Supervisor
    - name: Update supervisor config
      template: src=conf/supervisor.conf.j2 dest=/etc/supervisor/conf.d/wecron.conf
      sudo: True
      notify:
        - Load wecron with supervisord

#### uwsgi
    - name: Update uwsgi config
      template: src=conf/uwsgi.ini.j2 dest="{{ PROJ_HOME }}/uwsgi.ini"
      notify:
          - Load wecron with supervisord

### oneapm
    - name: Update oneapm config
      template: src=conf/blueware.ini.j2 dest="{{ PROJ_HOME }}/blueware.ini"

  handlers:
    # Handlers run in the order written
    - name: Start nginx
      sudo: True
      service: name=nginx state=started enabled=yes

    - name: Reload nginx
      sudo: True
      service: name=nginx state=reloaded

    - name: Install python dependencies
      pip:
          requirements: "{{ PROJ_HOME }}/requirements.txt"
          virtualenv: "{{ PROJ_VENV }}"
      notify:
          - Load wecron with supervisord

    - name: Start supervisor
      sudo: True
      service: name=supervisor state=started enabled=yes

    - name: Load wecron with supervisord
      sudo: True
      supervisorctl: name=wecron state=restarted

